// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: api/v1/nexusflow.proto

package nexusflowv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NexusFlowDaemon_CreateCell_FullMethodName   = "/nexusflow.v1.NexusFlowDaemon/CreateCell"
	NexusFlowDaemon_DestroyCell_FullMethodName  = "/nexusflow.v1.NexusFlowDaemon/DestroyCell"
	NexusFlowDaemon_AttachPID_FullMethodName    = "/nexusflow.v1.NexusFlowDaemon/AttachPID"
	NexusFlowDaemon_RunInCell_FullMethodName    = "/nexusflow.v1.NexusFlowDaemon/RunInCell"
	NexusFlowDaemon_WatchL3_FullMethodName      = "/nexusflow.v1.NexusFlowDaemon/WatchL3"
	NexusFlowDaemon_SetHugepages_FullMethodName = "/nexusflow.v1.NexusFlowDaemon/SetHugepages"
	NexusFlowDaemon_EvictForeign_FullMethodName = "/nexusflow.v1.NexusFlowDaemon/EvictForeign"
)

// NexusFlowDaemonClient is the client API for NexusFlowDaemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NexusFlowDaemonClient interface {
	CreateCell(ctx context.Context, in *CreateCellRequest, opts ...grpc.CallOption) (*CreateCellReply, error)
	DestroyCell(ctx context.Context, in *DestroyCellRequest, opts ...grpc.CallOption) (*DestroyCellReply, error)
	AttachPID(ctx context.Context, in *AttachPIDRequest, opts ...grpc.CallOption) (*AttachPIDReply, error)
	RunInCell(ctx context.Context, in *RunInCellRequest, opts ...grpc.CallOption) (NexusFlowDaemon_RunInCellClient, error)
	WatchL3(ctx context.Context, in *WatchL3Request, opts ...grpc.CallOption) (NexusFlowDaemon_WatchL3Client, error)
	SetHugepages(ctx context.Context, in *SetHugepagesRequest, opts ...grpc.CallOption) (*SetHugepagesReply, error)
	EvictForeign(ctx context.Context, in *EvictForeignRequest, opts ...grpc.CallOption) (*EvictForeignReply, error)
}

type nexusFlowDaemonClient struct {
	cc grpc.ClientConnInterface
}

func NewNexusFlowDaemonClient(cc grpc.ClientConnInterface) NexusFlowDaemonClient {
	return &nexusFlowDaemonClient{cc}
}

func (c *nexusFlowDaemonClient) CreateCell(ctx context.Context, in *CreateCellRequest, opts ...grpc.CallOption) (*CreateCellReply, error) {
	out := new(CreateCellReply)
	err := c.cc.Invoke(ctx, NexusFlowDaemon_CreateCell_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusFlowDaemonClient) DestroyCell(ctx context.Context, in *DestroyCellRequest, opts ...grpc.CallOption) (*DestroyCellReply, error) {
	out := new(DestroyCellReply)
	err := c.cc.Invoke(ctx, NexusFlowDaemon_DestroyCell_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusFlowDaemonClient) AttachPID(ctx context.Context, in *AttachPIDRequest, opts ...grpc.CallOption) (*AttachPIDReply, error) {
	out := new(AttachPIDReply)
	err := c.cc.Invoke(ctx, NexusFlowDaemon_AttachPID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusFlowDaemonClient) RunInCell(ctx context.Context, in *RunInCellRequest, opts ...grpc.CallOption) (NexusFlowDaemon_RunInCellClient, error) {
	stream, err := c.cc.NewStream(ctx, &NexusFlowDaemon_ServiceDesc.Streams[0], NexusFlowDaemon_RunInCell_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &nexusFlowDaemonRunInCellClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NexusFlowDaemon_RunInCellClient interface {
	Recv() (*RunInCellChunk, error)
	grpc.ClientStream
}

type nexusFlowDaemonRunInCellClient struct {
	grpc.ClientStream
}

func (x *nexusFlowDaemonRunInCellClient) Recv() (*RunInCellChunk, error) {
	m := new(RunInCellChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nexusFlowDaemonClient) WatchL3(ctx context.Context, in *WatchL3Request, opts ...grpc.CallOption) (NexusFlowDaemon_WatchL3Client, error) {
	stream, err := c.cc.NewStream(ctx, &NexusFlowDaemon_ServiceDesc.Streams[1], NexusFlowDaemon_WatchL3_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &nexusFlowDaemonWatchL3Client{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NexusFlowDaemon_WatchL3Client interface {
	Recv() (*L3Sample, error)
	grpc.ClientStream
}

type nexusFlowDaemonWatchL3Client struct {
	grpc.ClientStream
}

func (x *nexusFlowDaemonWatchL3Client) Recv() (*L3Sample, error) {
	m := new(L3Sample)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nexusFlowDaemonClient) SetHugepages(ctx context.Context, in *SetHugepagesRequest, opts ...grpc.CallOption) (*SetHugepagesReply, error) {
	out := new(SetHugepagesReply)
	err := c.cc.Invoke(ctx, NexusFlowDaemon_SetHugepages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusFlowDaemonClient) EvictForeign(ctx context.Context, in *EvictForeignRequest, opts ...grpc.CallOption) (*EvictForeignReply, error) {
	out := new(EvictForeignReply)
	err := c.cc.Invoke(ctx, NexusFlowDaemon_EvictForeign_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NexusFlowDaemonServer is the server API for NexusFlowDaemon service.
// All implementations must embed UnimplementedNexusFlowDaemonServer
// for forward compatibility
type NexusFlowDaemonServer interface {
	CreateCell(context.Context, *CreateCellRequest) (*CreateCellReply, error)
	DestroyCell(context.Context, *DestroyCellRequest) (*DestroyCellReply, error)
	AttachPID(context.Context, *AttachPIDRequest) (*AttachPIDReply, error)
	RunInCell(*RunInCellRequest, NexusFlowDaemon_RunInCellServer) error
	WatchL3(*WatchL3Request, NexusFlowDaemon_WatchL3Server) error
	SetHugepages(context.Context, *SetHugepagesRequest) (*SetHugepagesReply, error)
	EvictForeign(context.Context, *EvictForeignRequest) (*EvictForeignReply, error)
	mustEmbedUnimplementedNexusFlowDaemonServer()
}

// UnimplementedNexusFlowDaemonServer must be embedded to have forward compatible implementations.
type UnimplementedNexusFlowDaemonServer struct {
}

func (UnimplementedNexusFlowDaemonServer) CreateCell(context.Context, *CreateCellRequest) (*CreateCellReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCell not implemented")
}
func (UnimplementedNexusFlowDaemonServer) DestroyCell(context.Context, *DestroyCellRequest) (*DestroyCellReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyCell not implemented")
}
func (UnimplementedNexusFlowDaemonServer) AttachPID(context.Context, *AttachPIDRequest) (*AttachPIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttachPID not implemented")
}
func (UnimplementedNexusFlowDaemonServer) RunInCell(*RunInCellRequest, NexusFlowDaemon_RunInCellServer) error {
	return status.Errorf(codes.Unimplemented, "method RunInCell not implemented")
}
func (UnimplementedNexusFlowDaemonServer) WatchL3(*WatchL3Request, NexusFlowDaemon_WatchL3Server) error {
	return status.Errorf(codes.Unimplemented, "method WatchL3 not implemented")
}
func (UnimplementedNexusFlowDaemonServer) SetHugepages(context.Context, *SetHugepagesRequest) (*SetHugepagesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetHugepages not implemented")
}
func (UnimplementedNexusFlowDaemonServer) EvictForeign(context.Context, *EvictForeignRequest) (*EvictForeignReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvictForeign not implemented")
}
func (UnimplementedNexusFlowDaemonServer) mustEmbedUnimplementedNexusFlowDaemonServer() {}

// UnsafeNexusFlowDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NexusFlowDaemonServer will
// result in compilation errors.
type UnsafeNexusFlowDaemonServer interface {
	mustEmbedUnimplementedNexusFlowDaemonServer()
}

func RegisterNexusFlowDaemonServer(s grpc.ServiceRegistrar, srv NexusFlowDaemonServer) {
	s.RegisterService(&NexusFlowDaemon_ServiceDesc, srv)
}

func _NexusFlowDaemon_CreateCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusFlowDaemonServer).CreateCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusFlowDaemon_CreateCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusFlowDaemonServer).CreateCell(ctx, req.(*CreateCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusFlowDaemon_DestroyCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusFlowDaemonServer).DestroyCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusFlowDaemon_DestroyCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusFlowDaemonServer).DestroyCell(ctx, req.(*DestroyCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusFlowDaemon_AttachPID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachPIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusFlowDaemonServer).AttachPID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusFlowDaemon_AttachPID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusFlowDaemonServer).AttachPID(ctx, req.(*AttachPIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusFlowDaemon_RunInCell_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunInCellRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NexusFlowDaemonServer).RunInCell(m, &nexusFlowDaemonRunInCellServer{stream})
}

type NexusFlowDaemon_RunInCellServer interface {
	Send(*RunInCellChunk) error
	grpc.ServerStream
}

type nexusFlowDaemonRunInCellServer struct {
	grpc.ServerStream
}

func (x *nexusFlowDaemonRunInCellServer) Send(m *RunInCellChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _NexusFlowDaemon_WatchL3_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchL3Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NexusFlowDaemonServer).WatchL3(m, &nexusFlowDaemonWatchL3Server{stream})
}

type NexusFlowDaemon_WatchL3Server interface {
	Send(*L3Sample) error
	grpc.ServerStream
}

type nexusFlowDaemonWatchL3Server struct {
	grpc.ServerStream
}

func (x *nexusFlowDaemonWatchL3Server) Send(m *L3Sample) error {
	return x.ServerStream.SendMsg(m)
}

func _NexusFlowDaemon_SetHugepages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetHugepagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusFlowDaemonServer).SetHugepages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusFlowDaemon_SetHugepages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusFlowDaemonServer).SetHugepages(ctx, req.(*SetHugepagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusFlowDaemon_EvictForeign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvictForeignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusFlowDaemonServer).EvictForeign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusFlowDaemon_EvictForeign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusFlowDaemonServer).EvictForeign(ctx, req.(*EvictForeignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NexusFlowDaemon_ServiceDesc is the grpc.ServiceDesc for NexusFlowDaemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NexusFlowDaemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexusflow.v1.NexusFlowDaemon",
	HandlerType: (*NexusFlowDaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCell",
			Handler:    _NexusFlowDaemon_CreateCell_Handler,
		},
		{
			MethodName: "DestroyCell",
			Handler:    _NexusFlowDaemon_DestroyCell_Handler,
		},
		{
			MethodName: "AttachPID",
			Handler:    _NexusFlowDaemon_AttachPID_Handler,
		},
		{
			MethodName: "SetHugepages",
			Handler:    _NexusFlowDaemon_SetHugepages_Handler,
		},
		{
			MethodName: "EvictForeign",
			Handler:    _NexusFlowDaemon_EvictForeign_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunInCell",
			Handler:       _NexusFlowDaemon_RunInCell_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchL3",
			Handler:       _NexusFlowDaemon_WatchL3_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/nexusflow.proto",
}
