// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: api/v1/nexusflow.proto

package nexusflowv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCellRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CellId    string  `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	Cpus      []int32 `protobuf:"varint,2,rep,packed,name=cpus,proto3" json:"cpus,omitempty"`
	Mems      []int32 `protobuf:"varint,3,rep,packed,name=mems,proto3" json:"mems,omitempty"`
	Exclusive bool    `protobuf:"varint,4,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
}

func (x *CreateCellRequest) Reset() {
	*x = CreateCellRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_nexusflow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCellRequest) ProtoMessage() {}

func (x *CreateCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nexusflow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCellRequest.ProtoReflect.Descriptor instead.
func (*CreateCellRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_nexusflow_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCellRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *CreateCellRequest) GetCpus() []int32 {
	if x != nil {
		return x.Cpus
	}
	return nil
}

func (x *CreateCellRequest) GetMems() []int32 {
	if x != nil {
		return x.Mems
	}
	return nil
}

func (x *CreateCellRequest) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

type CreateCellReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CgroupPath string `protobuf:"bytes,1,opt,name=cgroup_path,json=cgroupPath,proto3" json:"cgroup_path,omitempty"`
}

func (x *CreateCellReply) Reset() {
	*x = CreateCellReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_nexusflow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCellReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCellReply) ProtoMessage() {}

func (x *CreateCellReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nexusflow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCellReply.ProtoReflect.Descriptor instead.
func (*CreateCellReply) Descriptor() ([]byte, []int) {
	return file_api_v1_nexusflow_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCellReply) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

type DestroyCellRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CellId string `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
}

func (x *DestroyCellRequest) Reset() {
	*x = DestroyCellRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_nexusflow_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyCellRequest) ProtoMessage() {}

func (x *DestroyCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nexusflow_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyCellRequest.ProtoReflect.Descriptor instead.
func (*DestroyCellRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_nexusflow_proto_rawDescGZIP(), []int{2}
}

func (x *DestroyCellRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

type DestroyCellReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DestroyCellReply) Reset() {
	*x = DestroyCellReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_nexusflow_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyCellReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyCellReply) ProtoMessage() {}

func (x *DestroyCellReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nexusflow_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyCellReply.ProtoReflect.Descriptor instead.
func (*DestroyCellReply) Descriptor() ([]byte, []int) {
	return file_api_v1_nexusflow_proto_rawDescGZIP(), []int{3}
}

type AttachPIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CellId string `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	Pid    int32  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *AttachPIDRequest) Reset() {
	*x = AttachPIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_nexusflow_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachPIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachPIDRequest) ProtoMessage() {}

func (x *AttachPIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nexusflow_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachPIDRequest.ProtoReflect.Descriptor instead.
func (*AttachPIDRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_nexusflow_proto_rawDescGZIP(), []int{4}
}

func (x *AttachPIDRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *AttachPIDRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type AttachPIDReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AttachPIDReply) Reset() {
	*x = AttachPIDReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_nexusflow_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachPIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachPIDReply) ProtoMessage() {}

func (x *AttachPIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nexusflow_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachPIDReply.ProtoReflect.Descriptor instead.
func (*AttachPIDReply) Descriptor() ([]byte, []int) {
	return file_api_v1_nexusflow_proto_rawDescGZIP(), []int{5}
}

type RunInCellRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CellId string   `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	Argv   []string `protobuf:"bytes,2,rep,name=argv,proto3" json:"argv,omitempty"`
}

func (x *RunInCellRequest) Reset() {
	*x = RunInCellRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_nexusflow_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunInCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunInCellRequest) ProtoMessage() {}

func (x *RunInCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nexusflow_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunInCellRequest.ProtoReflect.Descriptor instead.
func (*RunInCellRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_nexusflow_proto_rawDescGZIP(), []int{6}
}

func (x *RunInCellRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *RunInCellRequest) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

type RunInCellChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stdout   []byte `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr   []byte `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode int32  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Finished bool   `protobuf:"varint,4,opt,name=finished,proto3" json:"finished,omitempty"`
}

func (x *RunInCellChunk) Reset() {
	*x = RunInCellChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_nexusflow_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunInCellChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunInCellChunk) ProtoMessage() {}

func (x *RunInCellChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nexusflow_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunInCellChunk.ProtoReflect.Descriptor instead.
func (*RunInCellChunk) Descriptor() ([]byte, []int) {
	return file_api_v1_nexusflow_proto_rawDescGZIP(), []int{7}
}

func (x *RunInCellChunk) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *RunInCellChunk) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *RunInCellChunk) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RunInCellChunk) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

type WatchL3Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CellId     string `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	IntervalMs int32  `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
}

func (x *WatchL3Request) Reset() {
	*x = WatchL3Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_nexusflow_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchL3Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchL3Request) ProtoMessage() {}

func (x *WatchL3Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nexusflow_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchL3Request.ProtoReflect.Descriptor instead.
func (*WatchL3Request) Descriptor() ([]byte, []int) {
	return file_api_v1_nexusflow_proto_rawDescGZIP(), []int{8}
}

func (x *WatchL3Request) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *WatchL3Request) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type L3Sample struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LlcMisses     uint64 `protobuf:"varint,1,opt,name=llc_misses,json=llcMisses,proto3" json:"llc_misses,omitempty"`
	LlcReferences uint64 `protobuf:"varint,2,opt,name=llc_references,json=llcReferences,proto3" json:"llc_references,omitempty"`
	TimestampUnix int64  `protobuf:"varint,3,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
}

func (x *L3Sample) Reset() {
	*x = L3Sample{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_nexusflow_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L3Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L3Sample) ProtoMessage() {}

func (x *L3Sample) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nexusflow_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L3Sample.ProtoReflect.Descriptor instead.
func (*L3Sample) Descriptor() ([]byte, []int) {
	return file_api_v1_nexusflow_proto_rawDescGZIP(), []int{9}
}

func (x *L3Sample) GetLlcMisses() uint64 {
	if x != nil {
		return x.LlcMisses
	}
	return 0
}

func (x *L3Sample) GetLlcReferences() uint64 {
	if x != nil {
		return x.LlcReferences
	}
	return 0
}

func (x *L3Sample) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type SetHugepagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pages    int32  `protobuf:"varint,1,opt,name=pages,proto3" json:"pages,omitempty"`
	Pagesize string `protobuf:"bytes,2,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
}

func (x *SetHugepagesRequest) Reset() {
	*x = SetHugepagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_nexusflow_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetHugepagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHugepagesRequest) ProtoMessage() {}

func (x *SetHugepagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nexusflow_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHugepagesRequest.ProtoReflect.Descriptor instead.
func (*SetHugepagesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_nexusflow_proto_rawDescGZIP(), []int{10}
}

func (x *SetHugepagesRequest) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *SetHugepagesRequest) GetPagesize() string {
	if x != nil {
		return x.Pagesize
	}
	return ""
}

type SetHugepagesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReservedPages int32 `protobuf:"varint,1,opt,name=reserved_pages,json=reservedPages,proto3" json:"reserved_pages,omitempty"`
}

func (x *SetHugepagesReply) Reset() {
	*x = SetHugepagesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_nexusflow_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetHugepagesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHugepagesReply) ProtoMessage() {}

func (x *SetHugepagesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nexusflow_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHugepagesReply.ProtoReflect.Descriptor instead.
func (*SetHugepagesReply) Descriptor() ([]byte, []int) {
	return file_api_v1_nexusflow_proto_rawDescGZIP(), []int{11}
}

func (x *SetHugepagesReply) GetReservedPages() int32 {
	if x != nil {
		return x.ReservedPages
	}
	return 0
}

type EvictForeignRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpus   []int32 `protobuf:"varint,1,rep,packed,name=cpus,proto3" json:"cpus,omitempty"`
	DryRun bool    `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	// If missing, uses SIGSTOP (19). Use 15 for SIGTERM, 9 for SIGKILL.
	SignalNumber int32 `protobuf:"varint,3,opt,name=signal_number,json=signalNumber,proto3" json:"signal_number,omitempty"`
}

func (x *EvictForeignRequest) Reset() {
	*x = EvictForeignRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_nexusflow_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvictForeignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictForeignRequest) ProtoMessage() {}

func (x *EvictForeignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nexusflow_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictForeignRequest.ProtoReflect.Descriptor instead.
func (*EvictForeignRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_nexusflow_proto_rawDescGZIP(), []int{12}
}

func (x *EvictForeignRequest) GetCpus() []int32 {
	if x != nil {
		return x.Cpus
	}
	return nil
}

func (x *EvictForeignRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *EvictForeignRequest) GetSignalNumber() int32 {
	if x != nil {
		return x.SignalNumber
	}
	return 0
}

type EvictForeignReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessesStopped int32 `protobuf:"varint,1,opt,name=processes_stopped,json=processesStopped,proto3" json:"processes_stopped,omitempty"`
}

func (x *EvictForeignReply) Reset() {
	*x = EvictForeignReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_nexusflow_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvictForeignReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictForeignReply) ProtoMessage() {}

func (x *EvictForeignReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nexusflow_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictForeignReply.ProtoReflect.Descriptor instead.
func (*EvictForeignReply) Descriptor() ([]byte, []int) {
	return file_api_v1_nexusflow_proto_rawDescGZIP(), []int{13}
}

func (x *EvictForeignReply) GetProcessesStopped() int32 {
	if x != nil {
		return x.ProcessesStopped
	}
	return 0
}

var File_api_v1_nexusflow_proto protoreflect.FileDescriptor

var file_api_v1_nexusflow_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x66, 0x6c,
	0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x66,
	0x6c, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x22, 0x72, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63,
	0x65, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x65,
	0x6c, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x70, 0x75, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x70, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x6d, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x6d, 0x65, 0x6d, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x22, 0x32, 0x0a, 0x0f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1f, 0x0a,
	0x0b, 0x63, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x50, 0x61, 0x74, 0x68, 0x22, 0x2d,
	0x0a, 0x12, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x43, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x65, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x65, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0x12, 0x0a,
	0x10, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x43, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x3d, 0x0a, 0x10, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x50, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x65, 0x6c, 0x6c, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x65, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64,
	0x22, 0x10, 0x0a, 0x0e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x50, 0x49, 0x44, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x3f, 0x0a, 0x10, 0x52, 0x75, 0x6e, 0x49, 0x6e, 0x43, 0x65, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x65, 0x6c, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x65, 0x6c, 0x6c, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x76, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x72, 0x67, 0x76, 0x22, 0x79, 0x0a, 0x0e, 0x52, 0x75, 0x6e, 0x49, 0x6e, 0x43, 0x65, 0x6c, 0x6c,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73,
	0x74, 0x64, 0x65, 0x72, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x22, 0x4a,
	0x0a, 0x0e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x33, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x65, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x65, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x61, 0x6c, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x4d, 0x73, 0x22, 0x77, 0x0a, 0x08, 0x4c, 0x33,
	0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6c, 0x63, 0x5f, 0x6d, 0x69,
	0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6c, 0x6c, 0x63, 0x4d,
	0x69, 0x73, 0x73, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x6c, 0x63, 0x5f, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6c,
	0x6c, 0x63, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x55,
	0x6e, 0x69, 0x78, 0x22, 0x47, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x48, 0x75, 0x67, 0x65, 0x70, 0x61,
	0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x3a, 0x0a, 0x11,
	0x53, 0x65, 0x74, 0x48, 0x75, 0x67, 0x65, 0x70, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x5f, 0x70, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x64, 0x50, 0x61, 0x67, 0x65, 0x73, 0x22, 0x67, 0x0a, 0x13, 0x45, 0x76, 0x69, 0x63,
	0x74, 0x46, 0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x70, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x70, 0x75, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x72, 0x79, 0x5f, 0x72, 0x75, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x72, 0x79, 0x52, 0x75, 0x6e, 0x12, 0x23, 0x0a, 0x0d,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x22, 0x40, 0x0a, 0x11, 0x45, 0x76, 0x69, 0x63, 0x74, 0x46, 0x6f, 0x72, 0x65, 0x69, 0x67,
	0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x11, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x65, 0x73, 0x5f, 0x73, 0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x10, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x53, 0x74, 0x6f, 0x70,
	0x70, 0x65, 0x64, 0x32, 0xb3, 0x04, 0x0a, 0x0f, 0x4e, 0x65, 0x78, 0x75, 0x73, 0x46, 0x6c, 0x6f,
	0x77, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x4c, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x65, 0x6c, 0x6c, 0x12, 0x1f, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x66, 0x6c, 0x6f,
	0x77, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x65, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x66, 0x6c,
	0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x65, 0x6c, 0x6c,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4f, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79,
	0x43, 0x65, 0x6c, 0x6c, 0x12, 0x20, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x66, 0x6c, 0x6f, 0x77,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x43, 0x65, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x66, 0x6c,
	0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x43, 0x65, 0x6c,
	0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x49, 0x0a, 0x09, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x50, 0x49, 0x44, 0x12, 0x1e, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x66, 0x6c, 0x6f, 0x77, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x50, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x66, 0x6c, 0x6f, 0x77, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x50, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x4b, 0x0a, 0x09, 0x52, 0x75, 0x6e, 0x49, 0x6e, 0x43, 0x65, 0x6c, 0x6c, 0x12, 0x1e,
	0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75,
	0x6e, 0x49, 0x6e, 0x43, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75,
	0x6e, 0x49, 0x6e, 0x43, 0x65, 0x6c, 0x6c, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x30, 0x01, 0x12, 0x41,
	0x0a, 0x07, 0x57, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x33, 0x12, 0x1c, 0x2e, 0x6e, 0x65, 0x78, 0x75,
	0x73, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x33,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x66,
	0x6c, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x33, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x30,
	0x01, 0x12, 0x52, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x48, 0x75, 0x67, 0x65, 0x70, 0x61, 0x67, 0x65,
	0x73, 0x12, 0x21, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x65, 0x74, 0x48, 0x75, 0x67, 0x65, 0x70, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x66, 0x6c, 0x6f, 0x77,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x48, 0x75, 0x67, 0x65, 0x70, 0x61, 0x67, 0x65, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x52, 0x0a, 0x0c, 0x45, 0x76, 0x69, 0x63, 0x74, 0x46, 0x6f,
	0x72, 0x65, 0x69, 0x67, 0x6e, 0x12, 0x21, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x66, 0x6c, 0x6f,
	0x77, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x69, 0x63, 0x74, 0x46, 0x6f, 0x72, 0x65, 0x69, 0x67,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6e, 0x65, 0x78, 0x75, 0x73,
	0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x69, 0x63, 0x74, 0x46, 0x6f, 0x72,
	0x65, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x2d, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x2f, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x66, 0x6c, 0x6f, 0x77, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_nexusflow_proto_rawDescOnce sync.Once
	file_api_v1_nexusflow_proto_rawDescData = file_api_v1_nexusflow_proto_rawDesc
)

func file_api_v1_nexusflow_proto_rawDescGZIP() []byte {
	file_api_v1_nexusflow_proto_rawDescOnce.Do(func() {
		file_api_v1_nexusflow_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_nexusflow_proto_rawDescData)
	})
	return file_api_v1_nexusflow_proto_rawDescData
}

var file_api_v1_nexusflow_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_v1_nexusflow_proto_goTypes = []interface{}{
	(*CreateCellRequest)(nil),   // 0: nexusflow.v1.CreateCellRequest
	(*CreateCellReply)(nil),     // 1: nexusflow.v1.CreateCellReply
	(*DestroyCellRequest)(nil),  // 2: nexusflow.v1.DestroyCellRequest
	(*DestroyCellReply)(nil),    // 3: nexusflow.v1.DestroyCellReply
	(*AttachPIDRequest)(nil),    // 4: nexusflow.v1.AttachPIDRequest
	(*AttachPIDReply)(nil),      // 5: nexusflow.v1.AttachPIDReply
	(*RunInCellRequest)(nil),    // 6: nexusflow.v1.RunInCellRequest
	(*RunInCellChunk)(nil),      // 7: nexusflow.v1.RunInCellChunk
	(*WatchL3Request)(nil),      // 8: nexusflow.v1.WatchL3Request
	(*L3Sample)(nil),            // 9: nexusflow.v1.L3Sample
	(*SetHugepagesRequest)(nil), // 10: nexusflow.v1.SetHugepagesRequest
	(*SetHugepagesReply)(nil),   // 11: nexusflow.v1.SetHugepagesReply
	(*EvictForeignRequest)(nil), // 12: nexusflow.v1.EvictForeignRequest
	(*EvictForeignReply)(nil),   // 13: nexusflow.v1.EvictForeignReply
}
var file_api_v1_nexusflow_proto_depIdxs = []int32{
	0,  // 0: nexusflow.v1.NexusFlowDaemon.CreateCell:input_type -> nexusflow.v1.CreateCellRequest
	2,  // 1: nexusflow.v1.NexusFlowDaemon.DestroyCell:input_type -> nexusflow.v1.DestroyCellRequest
	4,  // 2: nexusflow.v1.NexusFlowDaemon.AttachPID:input_type -> nexusflow.v1.AttachPIDRequest
	6,  // 3: nexusflow.v1.NexusFlowDaemon.RunInCell:input_type -> nexusflow.v1.RunInCellRequest
	8,  // 4: nexusflow.v1.NexusFlowDaemon.WatchL3:input_type -> nexusflow.v1.WatchL3Request
	10, // 5: nexusflow.v1.NexusFlowDaemon.SetHugepages:input_type -> nexusflow.v1.SetHugepagesRequest
	12, // 6: nexusflow.v1.NexusFlowDaemon.EvictForeign:input_type -> nexusflow.v1.EvictForeignRequest
	1,  // 7: nexusflow.v1.NexusFlowDaemon.CreateCell:output_type -> nexusflow.v1.CreateCellReply
	3,  // 8: nexusflow.v1.NexusFlowDaemon.DestroyCell:output_type -> nexusflow.v1.DestroyCellReply
	5,  // 9: nexusflow.v1.NexusFlowDaemon.AttachPID:output_type -> nexusflow.v1.AttachPIDReply
	7,  // 10: nexusflow.v1.NexusFlowDaemon.RunInCell:output_type -> nexusflow.v1.RunInCellChunk
	9,  // 11: nexusflow.v1.NexusFlowDaemon.WatchL3:output_type -> nexusflow.v1.L3Sample
	11, // 12: nexusflow.v1.NexusFlowDaemon.SetHugepages:output_type -> nexusflow.v1.SetHugepagesReply
	13, // 13: nexusflow.v1.NexusFlowDaemon.EvictForeign:output_type -> nexusflow.v1.EvictForeignReply
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_nexusflow_proto_init() }
func file_api_v1_nexusflow_proto_init() {
	if File_api_v1_nexusflow_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_nexusflow_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCellRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_nexusflow_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCellReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_nexusflow_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyCellRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_nexusflow_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyCellReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_nexusflow_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachPIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_nexusflow_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachPIDReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_nexusflow_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunInCellRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_nexusflow_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunInCellChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_nexusflow_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchL3Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_nexusflow_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L3Sample); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_nexusflow_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetHugepagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_nexusflow_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetHugepagesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_nexusflow_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvictForeignRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_nexusflow_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvictForeignReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_nexusflow_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_nexusflow_proto_goTypes,
		DependencyIndexes: file_api_v1_nexusflow_proto_depIdxs,
		MessageInfos:      file_api_v1_nexusflow_proto_msgTypes,
	}.Build()
	File_api_v1_nexusflow_proto = out.File
	file_api_v1_nexusflow_proto_rawDesc = nil
	file_api_v1_nexusflow_proto_goTypes = nil
	file_api_v1_nexusflow_proto_depIdxs = nil
}
